TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0.05
  max_rotational_vel: 2
  min_in_place_vel_theta: 1

  acc_lim_th: 2
  acc_lim_x: 1

  meter_scoring: true
  holonomic_robot: false

  yaw_goal_tolerance: 0.34906585    #20 grados
  xy_goal_tolerance: 0.2            #20 cm