#This file contains common configuration options for the two costmaps used in the navigation stack for more details on the parameters in this file, and a full list of the parameters used by the costmaps, please see http://www.ros.org/wiki/costmap_2d


#Set the tolerance we're willing to have for tf transforms
transform_tolerance: 0.7

#Obstacle marking parameters
obstacle_range: 0.4
#max_obstacle_height: 2.0
raytrace_range: 0.5

#The footprint of the robot and associated padding
#footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
footprint_padding: 0.02
robot_radius: 0.1
#Cost function parameters
inflation_radius: 0.08
#cost_scaling_factor: 10.0

#The cost at which a cell is considered an obstacle when a map is read from the map_server
#lethal_cost_threshold: 100

#Configuration for the sensors that the costmap will use to update a map
observation_sources: multi_sonar
multi_sonar: {sensor_frame: base_link, data_type: LaserScan, topic: /arduino/sensor/multi_sonar, marking: true, clearing: true, expected_update_rate: 5}
#/arduino/sensors/multi_sonar: {data_type: LaserScan, expected_update_rate: 0.4, observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: 0.08}

#Recovery behaviors
recovery_behavior_enabled: true
clearing_rotation_allowed: true
conservative_reset_dist: 0.2

#planner_patience: 10