# For a direct USB cable connection, the port name is typically
# /dev/ttyACM# where is # is a number such as 0, 1, 2, etc
# For a wireless connection like XBee, the port is typically
# /dev/ttyUSB# where # is a number such as 0, 1, 2, etc.

port: /dev/ttyUSB0
baud: 57600
timeout: 0.1

rate: 50
sensorstate_rate: 10

use_base_controller: True
base_controller_rate: 10

# For a robot that uses base_footprint, change base_frame to base_footprint
base_frame: base_link

# === Robot drivetrain parameters
wheel_diameter: 0.0635
wheel_track: 0.14
encoder_resolution: 20
gear_reduction: 1
motors_reversed: False

# === PID parameters
Kp: 20
Kd: 5
Ki: 1
Ko: 1
accel_limit: 1.0

# === Sensor definitions.  Examples only - edit for your robot.
#     Sensor type can be one of the follow (case sensitive!):
#	  * Ping
#	  * GP2D12
#	  * Analog
#	  * Digital
#	  * PololuMotorCurrent
#	  * PhidgetsVoltage
#	  * PhidgetsCurrent (20 Amp, DC)


# El pin de los sonar realmente no es el pin, sino el elemento del vector de sonars que representan
sensors: {
  #motor_current_left:   {pin: 0, type: PololuMotorCurrent, rate: 5},
  #motor_current_right:  {pin: 1, type: PololuMotorCurrent, rate: 5},
  #ir_front_center:      {pin: 2, type: GP2D12, rate: 10},
  # sonar_verde:           {pin: 0, type: Ping, rate: 10},
  # sonar_azul:            {pin: 1, type: Ping, rate: 10},
  # sonar_amarillo:        {pin: 2, type: Ping, rate: 10},
  # sonar_rojo:            {pin: 3, type: Ping, rate: 10},
  # sonar_negro:           {pin: 4, type: Ping, rate: 10},
  # sonar_bicolor:         {pin: 5, type: Ping, rate: 10},
  #compass:               {pin: 21,type: Compass, rate: 10}, #No hay necesidad de publicarla porque se pide directamente cuando hace falta
  #line_follower:         {pin: 22, type: LineFollower, rate: 50}, #Mantenemos el sensor desabilitado para que así aumente la frecuencia de actualización de los sonar
  multi_sonar:           {pin: 0, type: MultiSonar, rate: 10}
  #arduino_led:          {pin: 13, type: Digital, rate: 5, direction: output}
}